# Generated by Django 5.0.3 on 2024-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provedores',
            options={'verbose_name_plural': 'Provedores'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name_plural': 'Servicos'},
        ),
        migrations.AddField(
            model_name='provedores',
            name='cnpj',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
