# Generated by Django 5.0.3 on 2024-04-01 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0003_remove_servicos_preco_precoservicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoservicos',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
